config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('game.urls') )
]

game/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'game'

urlpatterns = [
    path('info/<int:pk>', views.game_info, name='game_info'),
    path('result/', views.game_result, name='game_result'),
    path('podium/', views.game_podium, name='game_podium'),
    # main
    path("", views.main, name="main"),
    # # login
    path("login/", views.LoginView.as_view(), name="login"),
    # # logout
    path("logout/", views.log_out, name="logout"),
    path('attack/', views.game_attack, name='attack'),
    path('counterattack/<int:pk>/', views.game_counterattack, name='counterattack'),

    path('game_delete/<int:pk>/', views.game_delete, name='game_delete'),
]

game/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.enums import Choices
from django.contrib.auth.models import AbstractUser
from random import randint
import random

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=50)
    score = models.IntegerField(default=0)

    rank = models.PositiveIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class CardGame(models.Model):

    host = models.ForeignKey(User, on_delete=CASCADE, related_name='game_host')
    guest = models.ForeignKey(User, on_delete=CASCADE, related_name='game_guest')

    host_card = models.PositiveIntegerField(default=0)
    guest_card = models.PositiveIntegerField(default=0)

    is_end = models.BooleanField(default=False)

    rule = models.CharField(max_length=50, blank=True)

    result = models.CharField(max_length=50)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

game/forms.py
from django import forms
from . import models
from .models import User, CardGame

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    ### email & password validation
    def clean(self):
        email = self.cleaned_data.get("email")  # 오류가 없으면 Null
        password = self.cleaned_data.get("password")  # 오류가 없으면 Null
        try:
            user = models.User.objects.get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                raise forms.ValidationError("password is wrong!")
        except models.User.DoesNotExist:
            raise forms.ValidationError("user does not exist!")

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

class CardGameForm(forms.ModelForm):
    class Meta:
        model = CardGame
        fields = '__all__'

game/views.py
from django.shortcuts import render, redirect
from .models import CardGame, User
from django.views import View
from .forms import UserForm, CardGameForm
from . import forms
from django.contrib.auth import authenticate, login, logout
import random
from django.contrib.auth.decorators import login_required


# Create your views here.
def game_info(request, pk):
    game = CardGame.objects.get(id=pk)
    ctx = {'game': game}
    return render(request, 'game/info.html', context=ctx)


@login_required(login_url='')
def game_result(request):
    results = CardGame.objects.filter(
        host=request.user) | CardGame.objects.filter(guest=request.user)
    results = results.order_by('-pk')
    ctx = {'results': results}
    return render(request, 'game/result.html', context=ctx)


def game_podium(request):
    # 점수에 따라 ordering하여 가져옴
    users = User.objects.all().order_by('-score')

    players = User.objects.count()  # 유저 개수

    i = 1
    for user in users:
        user.rank = i
        i += 1

    ctx = {'users': users,
           "players": players,
           }
    return render(request, 'game/game_podium.html', context=ctx)


def main(request):
    return render(request, "game/main.html")


@login_required(login_url='')
def game_attack(request):
    if request.method == "POST":
        CardGame(host=request.user, guest=User.objects.get(
            username=request.POST['picked_cp']), host_card=request.POST['picked_card']).save()

        return redirect('game:game_result')
        #random_list = User.objects.get(id=pk).random_card_num()
    else:
        random_list = random.sample(range(1, 11), 5)
        counters = User.objects.exclude(username=request.user.username)
        # ctx = {
        #     'random_list': random_list,
        #     'counters' : counters,
        # }
    return render(request, "game/attack.html", {'random_list': random_list,
                                                'counters': counters, })


def game_counterattack(request, pk):
    game = CardGame.objects.get(id=pk)

    if request.method == "POST":
        g_card = request.POST['picked_card']

        rules = ['more', 'less']
        rand_rule = random.choice(rules)
        game.rule = rand_rule
        game.is_end = True
        h_card = int(game.host_card)
        g_card = int(g_card)
        game.guest_card = g_card

        if rand_rule == 'more':
            if h_card > g_card:
                game.result = 'win'

            elif h_card == g_card:
                game.result = 'draw'
            else:
                game.result = 'lose'
        else:
            if h_card < g_card:
                game.result = 'win'
            elif h_card == g_card:
                game.result = 'draw'
            else:
                game.result = 'lose'
        game.save()
        if game.result == 'win':
            game.host.score += h_card
            game.guest.score -= g_card

        elif game.result == 'lose':
            game.host.score -= h_card
            game.guest.score += g_card

        game.host.save()
        game.guest.save()

        return redirect('game:game_result')
        #random_list = User.objects.get(id=pk).random_card_num()
    else:
        random_list = random.sample(range(1, 11), 5)
        ctx = {
            'random_list': random_list,
            'game': game,
        }
    return render(request, "game/counterattack.html", context=ctx)


class LoginView(View):
    def get(self, request):
        form = forms.LoginForm()
        ctx = {
            "form": form,
        }
        return render(request, "game/login.html", ctx)

    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            # cleaned_data = {'email': email@dfksldf.com, 'password': 1234}
            if user is not None:
                login(request, user)
                return render(request, "game/success.html")

        return render(request, "game/login.html", {"form": form})


def log_out(request):
    logout(request)
    return render(request, "game/main.html")


def game_delete(request, pk):
    game = CardGame.objects.get(id=pk)
    game.delete()
    return redirect('game:game_result')

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Pirogram Cardgame</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Tourney:wght@500&display=swap" rel="stylesheet">
    </head>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="height: 70px; background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand teal-400" href="{% url 'game:main' %}" style="font-family: 'Tourney', cursive; font-size: 25px; margin-right: 30px;">PIROGRAM CARDGAME</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'game:attack' %}">게임하기</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'game:game_podium' %}">랭킹보기</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'game:logout' %}">로그아웃</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'game:login' %}">로그인</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <body>
        <div class="container-fluid justify-content-center text-center">
            {% block content %}

            {% endblock %}
        </div>
        
    </body>
    <footer id="footer">
        <div class="container-fluid justify-content-center text-center " style="height: 80px; background-color: #e3f2fd; position:absolute; bottom:0;">
            <br />
            <p class=" text-muted small mb-0">
                피로그래밍 15기 화이팅!!
            </p>
            <p class=" text-muted small mb-0">
                Made by PiroCardGame 5조 김건웅, 김세현, 김인엽, 서지운
            </p>
        </div>
    </footer>
</html>

game/templates/game/attack.html
{% extends "base.html" %}

{% block content %}

    <br/>
    <br/>
    <br/>
    <br/>
    <div class="d-flex flex-column justify-content-center align-items-center" style="margin-top: 200px; height: 345px;">
        <i class="fas fa-gamepad fa-4x" style="color: orange;"></i>
        <br />
        <form action="" method="POST" style="width: 450px;">
            {% csrf_token %}
            <h3>현재 플레이어: {{user.username}}</h3> 
            <br />
            <label for="picked_card">내가 고른 카드</label>
            <select name="picked_card">
                {% for num in random_list %}
                <option value="{{num}}">{{num}}</option>
                {% endfor %}
            </select>
            <br />
            <hr style="height: 4px; width: 85%; position: relative; left: 34px;"/>
            <br />
            <label for="picked_cp">상대방 </label>
            <select name="picked_cp">
                {% for cp in counters %}
                    <option value="{{cp}}">{{cp}}</option>
                {% endfor %}
            </select>
            <br />
            <br />
            {% comment %} <a href= "{% url "game:game_result" %}">공격하기!</a> {% endcomment %}
            <a href= "{% url "game:game_result" %}"><input type="submit" value="공격하기"  class="btn btn-outline-danger"/></a>
        </form>
    </div>
{% endblock %}

game/templates/game/counterattack.html
{% extends "base.html" %}

{% block content %}

<body>


    <br/>
    <br/>
    <br/>
    <br/>
    <div class="d-flex flex-column justify-content-center align-items-center" style="margin-top: 200px; height: 345px;">
        <i class="fas fa-gamepad fa-4x" style="color: orange;"></i>
        <form action="" method="POST" style="width: 450px;">
            {% csrf_token %}
            <h3>{{ game.host.username }}에게 반격하세요!</h3>

            <hr style="height: 2px;" />

            <h3>현재 플레이어: {{ game.guest.username }}</h3> 

            <label for="picked_card">내가 고른 카드</label>
            <select name="picked_card">
                {% for num in random_list %}
                <option value="{{num}}">{{num}}</option>
                {% endfor %}
            </select>


            <input type="submit" class="btn btn-sm btn-outline-danger" value="반격하기!">
        </form>
    </div>

    

{% endblock %}

game/templates/game/dashboard.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

game/templates/game/dashbord.html
{% block content %}

{% endblock %}

game/templates/game/game_podium.html
{% extends 'base.html' %}

{% block content %}


    <br/><br/><br/><br/><br/><br/>
    <div class="d-flex flex-column justify-content-center align-items-center" style="margin-top: 80px; height: 345px;">
        <i class="fas fa-gamepad fa-4x" style="color: orange;"></i>
        <br />
        <h3 style="font-weight: bold;">Piro 명예의 전당 </h3>
        <br />
        {% for user in users %}
            {% if user.rank == 1%}
                <p style="font-size: 25px; color: #FF0000; font-weight: bold">랭킹 {{user.rank }} 등 : {{ user.username}} 님 !  [ 총점수: {{ user.score }} ] </p>
            {% else %}
                <p style="font-size: 25px;">랭킹 {{user.rank }} 등 : {{ user.username}} 님 !  [ 총점수: {{ user.score }} ] </p>
            {% endif %}
        {% endfor %}  
        <hr style="height: 2px;" />
        <a href="{% url 'game:game_result' %}" class="btn btn-outline-success">전적목록</a>
    </div>

{% endblock %}

game/templates/game/info.html
{% extends 'base.html' %}

{% block content %}
    <br/>
    <br/>
    <br/>
    <br/>
    <div class="d-flex flex-column justify-content-center align-items-center" style="margin-top: 100px; height: 345px;">
        <i class="fas fa-gamepad fa-4x" style="color: orange;"></i>
        <br />
        <form action="" method="POST" style="width: 450px;">
            {% csrf_token %}
            <p style="font-weight: bold; font-size: 30px;">{{game.pk}}-{{game.host}} VS {{game.guest}}</p>
            {% if game.is_end == False %}
                {% if user.username == game.host.username %}
                    진행중...
                    <br />
                    나: {{ game.host_card }}
                    <br />
                    <a href="{% url 'game:game_delete' game.id %}" class="btn btn-outline-success" style="margin-bottom: 10px; margin-top: 10px;">게임 취소</a>
                    <br />
                    <a href="{% url 'game:game_result' %}" class="btn btn-outline-success">전적 목록</a>
                {% else %}
                    <a href="{% url 'game:counterattack' game.pk %}" class="btn btn-outline-success">대응하기</a>
                    <hr />
                    <a href="{% url 'game:game_result' %}" class="btn btn-outline-success">전적 목록</a>
                {% endif %}

            {% comment %} 게임 끝난 경우  {% endcomment %}
            {% else %}  
                <hr style="height: 2px;" />        
                {% if game.rule == 'more' %} 
                    숫자가 더 큰 사람이 대결에서 이깁니다.
                {% else %}
                    숫자가 더 작은 사람이 대결에서 이깁니다.
                {% endif %}

            <hr style="height: 2px;" />    

            나 ({{ user.username }}) :

            {% if user.username == game.host.username %}
                {{ game.host_card }}
                <br />
                {{ game.guest }}: {{ game.guest_card }}
            {% else %}
                {{ game.guest_card }}
                <br />
                {{ game.host }}: {{ game.host_card }}
            {% endif %}
            <hr style="height: 2px;" />
            {% if user.username == game.host.username %}
                결과: {{ user.username}} {{ game.result }}
            {% else %}
                결과: {{ user.username}}
                {% if game.result == 'win' %}
                    lose
                {% elif game.result == 'lose' %}
                    win
                {% else %}
                    draw
                {% endif %}
            {% endif %}
            
            <hr style="height: 2px;"/>
                {% if user.username == game.host.username %}
                    점수: {{ game.host.score }}
                {% else %}
                    점수: {{ game.guest.score }}
                {% endif %}
                <br />
                <a href="{% url 'game:game_result' %}" class="btn btn-outline-success" style="margin-top: 10px;">전적목록</a>
            {% endif %}
        </form>
    </div>
{% endblock content %}

game/templates/game/login.html
{% extends "base.html" %}

{% block content %}
    {% load socialaccount %}
    {% providers_media_js %}
    <div class="container-lg d-flex flex-column justify-content-center text-center" style="margin-top: 250px; width: 630px;">
        <i class="fas fa-sign-in-alt fa-5x" style="color: orange;"></i>
        <div class="row" style="margin-top: 40px;">
            <div class="col">
            <a class="fw-bold btn btn-outline-primary" href="/accounts/login">기존회원 로그인</a>
            <hr/>
            
            
            {% if user.is_authenticated %}
                <a href="/logout">로그아웃</a>
                <br>
                {{user.username}} 님이 로그인 중
            {% else %}
                <a class="fw-bold btn btn-outline-danger" href="{% provider_login_url 'google' %}">구글 로그인</a>
                <a class="fw-bold btn btn-outline-success" href="{% provider_login_url 'naver' %}">네이버 로그인</a>
            {% endif %}
            <hr/>
            <a class="fw-bold btn btn-outline-primary" href="/accounts/signup">신규 회원가입</a>
            </div>
        </div>
    </div>
{% endblock content %}

game/templates/game/main.html
{% extends 'base.html' %}

{% block content %}
    <section id="main">
        <div class="container-lg d-flex flex-column justify-content-center text-center vh-100">
            <div class="row">
                <i class="fas fa-users fa-5x" style="color: orange;"></i>
                <br />
                <div class="col" style="margin-top: 20px;">
                <h1 class="fw-bold">전 세계 피로그래머와 </h1>
                <h1 class="fw-bold">한 판 승부 숫자카드게임</h1>
                <br><br>

                {% if user.is_authenticated %}
                    <p class="fw-bolder">{{user.username}} 님이 로그인 중</p>
                    <br />
                    <a href="{% url 'game:attack' %}" class="btn btn-outline-success">게임하기</a>
                    <a href="{% url 'game:game_result' %}" class="btn btn-outline-success">전적보기</a>
                {%else%}
                    <span><a class="btn btn-outline-success" href="{% url 'game:login' %}" >로그인</a></span>
                    <span><a class="btn btn-outline-success" href="/accounts/signup">회원가입</a></span>
                {%endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

game/templates/game/result.html
{% extends 'base.html' %}

{% block content %}
    <br/>
    <br/>
    <br/>
    <br/>

    <div class='container-fluid d-flex justify-content-center text-center align-items-center flex-column' style="height: 345px; margin-top: 150px;">
        <i class="fas fa-gamepad fa-4x" style="color: orange;"></i>
        <br />
        <h1>게임 전적</h1>

        <span>현재 플레이어의 게임 전적을 보여주는 페이지입니다.</span>
        <p style="font-size: 20px; font-weight: bold;">현재 플레이어: {{user.username}}</p> 
        <br />

        {% for game in results %}
            <div>
                <span style="margin-right: 20px; font-weight: bold;">{{game.pk}}-{{game.host}}  VS  {{game.guest}}</span>
                {% if game.is_end == False %}
                    {% if user.username == game.host.username %}
                        진행중...
                        <a href="{% url 'game:game_delete' game.id %}" class="btn btn-sm btn-outline-danger" style="margin-left: 20px;">게임 취소</a>
                    {% else %}
                        <a href="{% url 'game:counterattack' game.pk %}" class="btn btn-sm btn-outline-danger">반격 하기</a>
                    {% endif %}
                {% else %}   <!--게임이 끝났을 때-->       
                {% comment %} {{ game.rule }} {% endcomment %}
                    {% if user.username == game.host.username %} 
                        {{ game.result }}
                    {% else %}
                        결과 :
                        {% if game.result == 'win' %}
                            패배
                        {% elif game.result == 'lose' %}
                            승리
                        {% else %}
                            무승부
                        {% endif %}
                    {% endif %}
                {% endif %}
                    
                <span><a href="{% url 'game:game_info' game.pk %}" class="btn btn-sm btn-outline-success">게임정보</a></span>
            </div>
            <br />
        {% endfor %}
    </div>
    
{% endblock %}